name: Build

on: [push]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: ISO
        run: |
          sudo apt-get install -y xorriso
          xorriso -as mkisofs -o alp.iso iso/
      - uses: actions/upload-artifact@v4
        with:
          name: alp-iso
          path: alp.iso
